### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by lianyiting00** [Musule/Navigation#5]
![image](https://user-images.githubusercontent.com/38458495/87142303-f0fb1c80-c2d6-11ea-916a-f158ae483256.png)

**Comment by liyinchigithub** [comment]
感谢小伙伴们报bug。
【原因】：开发环境使用node-sass 低版本会报错找不到部分文件，并且下载地址指向国外网络下载速度过慢。
【解决办法】：已开放node-sass版本高于4.11.0

1.删除Navigation文件夹下node_modules

2.终端窗口，执行命令

* 安装cnpm
```
npm install -g cnpm --registry=https://registry.npm.taobao.org
```

* 安装node-sass
```bash
cnpm install node-sass --save
```
* 安装
```bash
npm install
```
